version: '3'

services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: romkappa
      MARIADB_DATABASE: apirecette
